//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("statusModel", "FK__password__user_i__023D5A04", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.user), "password", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data.password), true)]
[assembly: EdmRelationshipAttribute("statusModel", "FK__status__user_id__07020F21", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.user), "status", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.status), true)]
[assembly: EdmRelationshipAttribute("statusModel", "FK__status_li__statu__0BC6C43E", "status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.status), "status_like", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.status_like), true)]
[assembly: EdmRelationshipAttribute("statusModel", "FK__status_vi__statu__117F9D94", "status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.status), "status_view", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.status_view), true)]
[assembly: EdmRelationshipAttribute("statusModel", "FK__status_li__user___0CBAE877", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data.user), "status_like", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.status_like), true)]
[assembly: EdmRelationshipAttribute("statusModel", "FK__status_vi__user___1273C1CD", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data.user), "status_view", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.status_view), true)]

#endregion

namespace Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<password> passwords
        {
            get
            {
                if ((_passwords == null))
                {
                    _passwords = base.CreateObjectSet<password>("passwords");
                }
                return _passwords;
            }
        }
        private ObjectSet<password> _passwords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<status> status
        {
            get
            {
                if ((_status == null))
                {
                    _status = base.CreateObjectSet<status>("status");
                }
                return _status;
            }
        }
        private ObjectSet<status> _status;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<status_like> status_like
        {
            get
            {
                if ((_status_like == null))
                {
                    _status_like = base.CreateObjectSet<status_like>("status_like");
                }
                return _status_like;
            }
        }
        private ObjectSet<status_like> _status_like;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<status_view> status_view
        {
            get
            {
                if ((_status_view == null))
                {
                    _status_view = base.CreateObjectSet<status_view>("status_view");
                }
                return _status_view;
            }
        }
        private ObjectSet<status_view> _status_view;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the passwords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopasswords(password password)
        {
            base.AddObject("passwords", password);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the status EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostatus(status status)
        {
            base.AddObject("status", status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the status_like EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostatus_like(status_like status_like)
        {
            base.AddObject("status_like", status_like);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the status_view EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostatus_view(status_view status_view)
        {
            base.AddObject("status_view", status_view);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="statusModel", Name="password")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class password : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new password object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static password Createpassword(global::System.Int32 user_id)
        {
            password password = new password();
            password.user_id = user_id;
            return password;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String salt
        {
            get
            {
                return _salt;
            }
            set
            {
                OnsaltChanging(value);
                ReportPropertyChanging("salt");
                _salt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("salt");
                OnsaltChanged();
            }
        }
        private global::System.String _salt;
        partial void OnsaltChanging(global::System.String value);
        partial void OnsaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] password1
        {
            get
            {
                return StructuralObject.GetValidValue(_password1);
            }
            set
            {
                Onpassword1Changing(value);
                ReportPropertyChanging("password1");
                _password1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password1");
                Onpassword1Changed();
            }
        }
        private global::System.Byte[] _password1;
        partial void Onpassword1Changing(global::System.Byte[] value);
        partial void Onpassword1Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__password__user_i__023D5A04", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__password__user_i__023D5A04", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__password__user_i__023D5A04", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__password__user_i__023D5A04", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("statusModel.FK__password__user_i__023D5A04", "user", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="statusModel", Name="status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new status object.
        /// </summary>
        /// <param name="status_id">Initial value of the status_id property.</param>
        /// <param name="message">Initial value of the message property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="date_added">Initial value of the date_added property.</param>
        public static status Createstatus(global::System.Int32 status_id, global::System.String message, global::System.Int32 user_id, global::System.DateTime date_added)
        {
            status status = new status();
            status.status_id = status_id;
            status.message = message;
            status.user_id = user_id;
            status.date_added = date_added;
            return status;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_id
        {
            get
            {
                return _status_id;
            }
            set
            {
                if (_status_id != value)
                {
                    Onstatus_idChanging(value);
                    ReportPropertyChanging("status_id");
                    _status_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("status_id");
                    Onstatus_idChanged();
                }
            }
        }
        private global::System.Int32 _status_id;
        partial void Onstatus_idChanging(global::System.Int32 value);
        partial void Onstatus_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_added
        {
            get
            {
                return _date_added;
            }
            set
            {
                Ondate_addedChanging(value);
                ReportPropertyChanging("date_added");
                _date_added = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_added");
                Ondate_addedChanged();
            }
        }
        private global::System.DateTime _date_added;
        partial void Ondate_addedChanging(global::System.DateTime value);
        partial void Ondate_addedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status__user_id__07020F21", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__status__user_id__07020F21", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__status__user_id__07020F21", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__status__user_id__07020F21", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("statusModel.FK__status__user_id__07020F21", "user", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status_li__statu__0BC6C43E", "status_like")]
        public EntityCollection<status_like> status_like
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<status_like>("statusModel.FK__status_li__statu__0BC6C43E", "status_like");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<status_like>("statusModel.FK__status_li__statu__0BC6C43E", "status_like", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status_vi__statu__117F9D94", "status_view")]
        public EntityCollection<status_view> status_view
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<status_view>("statusModel.FK__status_vi__statu__117F9D94", "status_view");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<status_view>("statusModel.FK__status_vi__statu__117F9D94", "status_view", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="statusModel", Name="status_like")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class status_like : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new status_like object.
        /// </summary>
        /// <param name="status_like_id">Initial value of the status_like_id property.</param>
        /// <param name="status_id">Initial value of the status_id property.</param>
        /// <param name="ip_address">Initial value of the ip_address property.</param>
        /// <param name="date_added">Initial value of the date_added property.</param>
        public static status_like Createstatus_like(global::System.Int32 status_like_id, global::System.Int32 status_id, global::System.String ip_address, global::System.DateTime date_added)
        {
            status_like status_like = new status_like();
            status_like.status_like_id = status_like_id;
            status_like.status_id = status_id;
            status_like.ip_address = ip_address;
            status_like.date_added = date_added;
            return status_like;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_like_id
        {
            get
            {
                return _status_like_id;
            }
            set
            {
                if (_status_like_id != value)
                {
                    Onstatus_like_idChanging(value);
                    ReportPropertyChanging("status_like_id");
                    _status_like_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("status_like_id");
                    Onstatus_like_idChanged();
                }
            }
        }
        private global::System.Int32 _status_like_id;
        partial void Onstatus_like_idChanging(global::System.Int32 value);
        partial void Onstatus_like_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_id
        {
            get
            {
                return _status_id;
            }
            set
            {
                Onstatus_idChanging(value);
                ReportPropertyChanging("status_id");
                _status_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_id");
                Onstatus_idChanged();
            }
        }
        private global::System.Int32 _status_id;
        partial void Onstatus_idChanging(global::System.Int32 value);
        partial void Onstatus_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ip_address
        {
            get
            {
                return _ip_address;
            }
            set
            {
                Onip_addressChanging(value);
                ReportPropertyChanging("ip_address");
                _ip_address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ip_address");
                Onip_addressChanged();
            }
        }
        private global::System.String _ip_address;
        partial void Onip_addressChanging(global::System.String value);
        partial void Onip_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_added
        {
            get
            {
                return _date_added;
            }
            set
            {
                Ondate_addedChanging(value);
                ReportPropertyChanging("date_added");
                _date_added = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_added");
                Ondate_addedChanged();
            }
        }
        private global::System.DateTime _date_added;
        partial void Ondate_addedChanging(global::System.DateTime value);
        partial void Ondate_addedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int32> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int32> value);
        partial void Onuser_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status_li__statu__0BC6C43E", "status")]
        public status status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<status>("statusModel.FK__status_li__statu__0BC6C43E", "status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<status>("statusModel.FK__status_li__statu__0BC6C43E", "status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<status> statusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<status>("statusModel.FK__status_li__statu__0BC6C43E", "status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<status>("statusModel.FK__status_li__statu__0BC6C43E", "status", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status_li__user___0CBAE877", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__status_li__user___0CBAE877", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__status_li__user___0CBAE877", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__status_li__user___0CBAE877", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("statusModel.FK__status_li__user___0CBAE877", "user", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="statusModel", Name="status_view")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class status_view : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new status_view object.
        /// </summary>
        /// <param name="status_view_id">Initial value of the status_view_id property.</param>
        /// <param name="status_id">Initial value of the status_id property.</param>
        /// <param name="ip_address">Initial value of the ip_address property.</param>
        /// <param name="date_added">Initial value of the date_added property.</param>
        public static status_view Createstatus_view(global::System.Int32 status_view_id, global::System.Int32 status_id, global::System.String ip_address, global::System.DateTime date_added)
        {
            status_view status_view = new status_view();
            status_view.status_view_id = status_view_id;
            status_view.status_id = status_id;
            status_view.ip_address = ip_address;
            status_view.date_added = date_added;
            return status_view;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_view_id
        {
            get
            {
                return _status_view_id;
            }
            set
            {
                if (_status_view_id != value)
                {
                    Onstatus_view_idChanging(value);
                    ReportPropertyChanging("status_view_id");
                    _status_view_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("status_view_id");
                    Onstatus_view_idChanged();
                }
            }
        }
        private global::System.Int32 _status_view_id;
        partial void Onstatus_view_idChanging(global::System.Int32 value);
        partial void Onstatus_view_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_id
        {
            get
            {
                return _status_id;
            }
            set
            {
                Onstatus_idChanging(value);
                ReportPropertyChanging("status_id");
                _status_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_id");
                Onstatus_idChanged();
            }
        }
        private global::System.Int32 _status_id;
        partial void Onstatus_idChanging(global::System.Int32 value);
        partial void Onstatus_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ip_address
        {
            get
            {
                return _ip_address;
            }
            set
            {
                Onip_addressChanging(value);
                ReportPropertyChanging("ip_address");
                _ip_address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ip_address");
                Onip_addressChanged();
            }
        }
        private global::System.String _ip_address;
        partial void Onip_addressChanging(global::System.String value);
        partial void Onip_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_added
        {
            get
            {
                return _date_added;
            }
            set
            {
                Ondate_addedChanging(value);
                ReportPropertyChanging("date_added");
                _date_added = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_added");
                Ondate_addedChanged();
            }
        }
        private global::System.DateTime _date_added;
        partial void Ondate_addedChanging(global::System.DateTime value);
        partial void Ondate_addedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int32> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int32> value);
        partial void Onuser_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status_vi__statu__117F9D94", "status")]
        public status status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<status>("statusModel.FK__status_vi__statu__117F9D94", "status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<status>("statusModel.FK__status_vi__statu__117F9D94", "status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<status> statusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<status>("statusModel.FK__status_vi__statu__117F9D94", "status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<status>("statusModel.FK__status_vi__statu__117F9D94", "status", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status_vi__user___1273C1CD", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__status_vi__user___1273C1CD", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__status_vi__user___1273C1CD", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("statusModel.FK__status_vi__user___1273C1CD", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("statusModel.FK__status_vi__user___1273C1CD", "user", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="statusModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="user_name">Initial value of the user_name property.</param>
        public static user Createuser(global::System.Int32 user_id, global::System.String user_name)
        {
            user user = new user();
            user.user_id = user_id;
            user.user_name = user_name;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                Onuser_nameChanging(value);
                ReportPropertyChanging("user_name");
                _user_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_name");
                Onuser_nameChanged();
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__password__user_i__023D5A04", "password")]
        public password password
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<password>("statusModel.FK__password__user_i__023D5A04", "password").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<password>("statusModel.FK__password__user_i__023D5A04", "password").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<password> passwordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<password>("statusModel.FK__password__user_i__023D5A04", "password");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<password>("statusModel.FK__password__user_i__023D5A04", "password", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status__user_id__07020F21", "status")]
        public EntityCollection<status> status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<status>("statusModel.FK__status__user_id__07020F21", "status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<status>("statusModel.FK__status__user_id__07020F21", "status", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status_li__user___0CBAE877", "status_like")]
        public EntityCollection<status_like> status_like
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<status_like>("statusModel.FK__status_li__user___0CBAE877", "status_like");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<status_like>("statusModel.FK__status_li__user___0CBAE877", "status_like", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("statusModel", "FK__status_vi__user___1273C1CD", "status_view")]
        public EntityCollection<status_view> status_view
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<status_view>("statusModel.FK__status_vi__user___1273C1CD", "status_view");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<status_view>("statusModel.FK__status_vi__user___1273C1CD", "status_view", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
